function [R, B] = generate_reward(nswitches)
[R, B] = deal(cell(nswitches, 1));

for i = 1:nswitches
    R{i} = [randsample(1:5, 40, true),...
        randsample(1:3, 40, true),...
        randsample(1:5, 40, true),...
        randsample(3:5, 40, true)]';

    B{i} = [ones(40, 1)*1;...
        ones(40, 1)*3;...
        ones(40, 1)*1;...
        ones(40, 1)*2];
end

R = cell2mat(R);
B = cell2mat(B);
end