function [blk_rat_mean, blk_rat_sem, blk_mdl_mean, blk_mdl_sem] =...
    ratAndMdlWTCurves(ratname, BestFit)

A = BestFit.(ratname).Test.ratTrial;
usethese = A.catch & A.optout & ~isnan(A.wait_time);
rew = convertreward(A.reward(usethese));
blk = A.block(usethese);

wt_rat = A.wait_time(usethese);
wt_mdl = BestFit.(ratname).Test.WTMdl(usethese);

blk_rat_mean =...
    [arrayfun(@(r) mean(wt_rat(rew==r & blk==1)), 1:5)
    arrayfun(@(r) mean(wt_rat(rew==r & blk==2)), 1:5);...
    arrayfun(@(r) mean(wt_rat(rew==r & blk==3)), 1:5)];
blk_rat_sem =...
    [arrayfun(@(r) std(wt_rat(rew==r & blk==1))./...
    sqrt(sum(rew==r & blk==1)), 1:5);...
    arrayfun(@(r) std(wt_rat(rew==r & blk==2))./...
    sqrt(sum(rew==r & blk==2)), 1:5);...
    arrayfun(@(r) std(wt_rat(rew==r & blk==3))./...
    sqrt(sum(rew==r & blk==3)), 1:5)];

blk_mdl_mean =...
    [arrayfun(@(r) mean(wt_mdl(rew==r & blk==1)), 1:5);...
    arrayfun(@(r) mean(wt_mdl(rew==r & blk==2)), 1:5);...
    arrayfun(@(r) mean(wt_mdl(rew==r & blk==3)), 1:5)];
blk_mdl_sem =...
    [arrayfun(@(r) std(wt_mdl(rew==r & blk==1))./...
    sqrt(sum(rew==r & blk==1)), 1:5);...
    arrayfun(@(r) std(wt_mdl(rew==r & blk==2))./...
    sqrt(sum(rew==r & blk==2)), 1:5);...
    arrayfun(@(r) std(wt_mdl(rew==r & blk==3))./...
    sqrt(sum(rew==r & blk==3)), 1:5)];
end